# -*- coding: utf-8 -*-
"""Requisicao Datajud.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JUTRtvhfWFPAGgtP_PNlhOTGUeKftvLn
"""

import requests
import json
import pandas as pd

url = "https://api-publica.datajud.cnj.jus.br/api_publica_tjdft/_search"

payload = json.dumps({
    "query": {
        "bool": {
            "must": [
                {"match": {"classe.codigo": 1116}},
                 {"match": {"orgaoJulgador.codigo": 13597}}
                ]
            }
        }
}
)

# Key API Datajud
headers = {
    'Authorization': 'ApiKey cDZHYzlZa0JadVREZDJCendQbXY6SkJlTzNjLV9TRENyQk1RdnFKZGRQdw==',
    'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)

# Converte a saída em um df Pandas,  saída em excel
df = pd.json_normalize(response.json()["hits"]["hits"])
df.to_excel("resultado.xlsx")